"use strict";
// Generated by https://quicktype.io
Object.defineProperty(exports, "__esModule", { value: true });
exports.Text = void 0;
var Text;
(function (Text) {
    Text["Clear"] = "Clear";
    Text["Cloudy"] = "Cloudy";
    Text["HeavyRain"] = "Heavy rain";
    Text["HeavyRainAtTimes"] = "Heavy rain at times";
    Text["LightRainShower"] = "Light rain shower";
    Text["ModerateOrHeavyRainShower"] = "Moderate or heavy rain shower";
    Text["ModerateOrHeavyRainWithThunder"] = "Moderate or heavy rain with thunder";
    Text["ModerateRain"] = "Moderate rain";
    Text["PartlyCloudy"] = "Partly cloudy";
    Text["PatchyRainPossible"] = "Patchy rain possible";
    Text["Sunny"] = "Sunny";
})(Text || (exports.Text = Text = {}));
